apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-server-app-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo-server-app
  template:
    metadata:
      labels:
        app: todo-server-app
    spec:
      containers:
      - image: doijoy46/todo-server-kubernetes-app:v5
        name: container1
        ports:
        - containerPort: 5000
        imagePullPolicy: IfNotPresent